### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.ViewParent.requestDisallowInterceptTouchEvent(boolean)' on a null object reference  

### ISSUE THREAD

**Issue by ChetanCul** [whilu/AndroidTagView#35]
When I delete a tag and immediately click on the tagContainerLayout which was holding that tag then the app crash with the above error. I am posting my full stack trace hope it will help in resolving the issue.
Full error stack trace : 
`12-02 14:08:26.341 21385-21385/com.demo.app E/InputEventReceiver: Exception dispatching input event.
12-02 14:08:26.343 21385-21385/com.demo.app E/UncaughtException: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.ViewParent.requestDisallowInterceptTouchEvent(boolean)' on a null object reference
                                                                                at co.lujun.androidtagview.b.dispatchTouchEvent(SourceFile:228)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:63)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:63)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                                at ``android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)`

**Comment by whilu** [comment]
Thanks for your feedback, I will check the problem as soon as possible!

**Comment by whilu** [comment]
I have tested the code but can't reproduce the bug. I added a protection to the code based on your exception.😄

**Comment by ChetanCul** [comment]
I will try it again n let's not close it now. If there's no issue then I will close it.

**Comment by ChetanCul** [comment]
Yeah It's working fine now.

**Comment by RameshJhajharia** [comment]
Hi,

I am getting the same issue. Here is stack trace:

Exception java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.ViewParent.requestDisallowInterceptTouchEvent(boolean)' on a null object reference
co.lujun.androidtagview.TagView.dispatchTouchEvent (TagView.java:228)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2555)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2254)

**Comment by whilu** [comment]
@RameshJhajharia The bug fixed version doesn't upload to jCenter, you can try this dependency:

[https://jitpack.io/#whilu/AndroidTagView/-SNAPSHOT](https://jitpack.io/#whilu/AndroidTagView/-SNAPSHOT)

code like this:
```gradle
allprojects {
	repositories {
		maven { url 'https://jitpack.io' }
        }
}

dependencies {
	compile 'com.github.whilu:AndroidTagView:-SNAPSHOT'
}
```

Thanks!

**Comment by RameshJhajharia** [comment]
@whilu Thanks. I have updated the dependency.

**Comment by appss** [comment]
@whilu Hey, when it will be updated?

**Comment by whilu** [comment]
@appss v1.0.6 has uploaded to jCenter, try it😁

**Comment by appss** [comment]
Ok. I implemented from https://github.com/whilu/AndroidTagView. As per readme, i had used version 1.0.5.
