### ISSUE TITLE
crash，空指针了

### ISSUE THREAD

**Issue by hardlove** [whilu/AndroidTagView#38]
java.lang.NullPointerException: Attempt to invoke virtual method 'int co.lujun.androidtagview.TagContainerLayout.getTagViewState()' on a null object reference
                                                                              at co.lujun.androidtagview.TagView$1.run(TagView.java:115)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:158)

**Comment by whilu** [comment]
@hardlove 请问你是在什么操作下触发这个错误的？

**Comment by nottoobad** [comment]
#53 看堆栈信息好像是同一个问题

**Comment by BhargavVGhodasara** [comment]
i also get same issue.

**Comment by LawrenceStent** [comment]
Can you give the solution in english please?
