### ISSUE TITLE
同时长按2个tag会崩溃，内附stacktrace

### ISSUE THREAD

**Issue by nottoobad** [whilu/AndroidTagView#53]
java.lang.NullPointerException: Attempt to invoke virtual method 'int co.lujun.androidtagview.TagContainerLayout.getTagViewState()' on a null object reference
                                                                      at co.lujun.androidtagview.TagView$1.run(TagView.java:120)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5910)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by whilu** [comment]
@nottoobad 
谢谢你的反馈，我测试了一下你说的这种情况（同时长按两个 TagView），好像没有出现 crash，能提供一下具体的机型、系统吗？
