### ISSUE TITLE
1.1.7无法运行

### ISSUE THREAD

**Issue by tianyajuechen** [whilu/AndroidTagView#95]
编译能通过，但是app一运行就报错：
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lvic.loyalvalley/com.lvic.loyalvalley.activity.SearchActivity}: android.view.InflateException: Binary XML file line #111: Binary XML file line #111: Error inflating class co.lujun.androidtagview.TagContainerLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.view.InflateException: Binary XML file line #111: Binary XML file line #111: Error inflating class co.lujun.androidtagview.TagContainerLayout
     Caused by: android.view.InflateException: Binary XML file line #111: Error inflating class co.lujun.androidtagview.TagContainerLayout
     Caused by: java.lang.reflect.InvocationTargetException

换成1.15版本就好了

**Comment by whilu** [comment]
In v1.1.7, the library use implementation
'androidx.appcompat:appcompat:1.0.1' as the appcompat, so you need to use
[implementation 'androidx.appcompat:appcompat:1.0.1'] in your project
build.grade file, and set the compileSdkVersion to 28. The lib will fix
this problem in next version.

tianyajuechen <notifications@github.com>于2019年2月22日 周五16:02写道：

**Comment by moo611** [comment]
希望能尽快解决，目前测试只有1.1.2老版本能正常使用。谢谢。

**Comment by bestchangge** [comment]
一样的问题

**Comment by mggrbk** [comment]
+1
